export const url = '54.174.6.229'
export const port = '8181'
export const entryPoint = '/api/cursos'
export const entryPointSearchCourse = '/api/buscarCurso'
export const entryPointSearchCourseName = '/api/nombreCurso'