export const url = '54.146.182.164'
export const port = '8181'
export const entryPoint = '/api/cursos'
export const entryPointSearchCourse = '/api/buscarCurso'
export const entryPointSearchCourseComplete = '/api/cursoCompleto'
export const entryPointSearchCoursesIds = '/api/cursosId'
